// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwyjlhjrfhapnzbizqvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53eWpsaGpyZmhhcG56Yml6cXZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwNzE3MjUsImV4cCI6MjA4NzY0NzcyNX0.5ubb00zSLwjyH-bHaPjHhkFmLJjQBngUt2uK1N-rqdY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});